<template>
  <div class="leaderboard country-leaderboard">
    <div class="title-container">
      <h2 class="leaderboard-title animate-glitch">🌍 TOP COUNTRIES</h2>
      <p class="leaderboard-description">Most wraps generated by country.</p>
      <div class="title-underline"></div>
    </div>
    
    <div v-if="isLoading" class="leaderboard-loading">
      <div class="scanner"></div>
      ANALYZING COUNTRIES...
    </div>
    
    <div v-else-if="countries.length === 0" class="leaderboard-empty">
      NO COUNTRY DATA AVAILABLE.
    </div>
    
    <div v-else class="leaderboard-list">
      <button
        v-for="(country, index) in countries"
        :key="country.country"
        class="leaderboard-item"
        :class="[
          { 'top-1': index === 0, 'top-2': index === 1, 'top-3': index === 2 },
          index % 2 === 0 ? 'race-in-right' : 'race-in-left'
        ]"
        :style="{ animationDelay: `${index * 100}ms` }"
      >
        <div class="rank-section">
          <div class="rank-badge">{{ index + 1 }}</div>
          <div class="country-flag-large">{{ getCountryFlag(country.country) }}</div>
        </div>
        <div class="country-info">
          <div class="country-name-row">
            <span class="country-name">{{ getCountryName(country.country) }}</span>
          </div>
          <div class="country-stats">
            <span class="stat-value highlight">{{ country.totalViews.toLocaleString() }}</span>
            <span class="stat-label">WRAPS</span>
            <span class="separator">/</span>
            <span class="stat-value">{{ country.athleteCount }}</span>
            <span class="stat-label">ATHLETES</span>
          </div>
        </div>
        <div class="item-glitch"></div>
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { getCountryFlag } from '@/utils/countryFlags'

interface CountryData {
  country: string
  totalViews: number
  athleteCount: number
}

const countries = ref<CountryData[]>([])
const isLoading = ref(true)

onMounted(async () => {
  isLoading.value = true
  try {
    const response = await fetch('/data/country_stats_2025.json')
    console.log('Country leaderboard fetch response:', response.status, response.ok)
    if (response.ok) {
      const data = await response.json()
      console.log('Country data loaded:', data)
      countries.value = data
    } else {
      console.error('Failed to fetch country data:', response.status)
    }
  } catch (error) {
    console.error('Error loading country leaderboard:', error)
  } finally {
    isLoading.value = false
  }
})

function getCountryName(code: string) {
  // You could add a mapping here, but for now just return the code
  return code
}
</script>

<style scoped>
.leaderboard {
  padding: var(--spacing-md);
  background: rgba(255, 255, 255, 0.02);
  border: 1px solid rgba(255, 255, 255, 0.05);
  border-top: 3px solid var(--color-accent-primary);
  position: relative;
  overflow: hidden;
}

@media (min-width: 768px) {
  .leaderboard {
    padding: var(--spacing-lg);
  }
}

.title-container {
  text-align: center;
  margin-bottom: var(--spacing-xl);
  position: relative;
  z-index: 2;
}

.leaderboard-title {
  font-family: var(--font-family-heading);
  font-size: clamp(1.5rem, 6vw, 2.5rem);
  color: white;
  margin: 0;
  letter-spacing: 2px;
  text-transform: uppercase;
  font-style: italic;
  font-weight: 900;
  text-shadow: 2px 2px 0px var(--color-accent-secondary);
}

.leaderboard-description {
  font-size: 0.85rem;
  color: rgba(255, 255, 255, 0.5);
  margin: 4px 0 0 0;
  font-family: var(--font-family-base);
  letter-spacing: 0.5px;
  text-transform: uppercase;
  font-weight: 500;
}

@media (min-width: 768px) {
  .leaderboard-description {
    font-size: 1rem;
    margin-top: 8px;
  }
}

.title-underline {
  width: 40px;
  height: 3px;
  background: var(--color-accent-primary);
  margin: var(--spacing-sm) auto 0;
  box-shadow: 0 0 10px var(--color-accent-primary);
}

.leaderboard-loading,
.leaderboard-empty {
  text-align: center;
  padding: var(--spacing-3xl);
  color: rgba(255, 255, 255, 0.4);
  font-family: var(--font-family-heading);
  font-size: 0.9rem;
  letter-spacing: 2px;
}

.scanner {
  width: 40px;
  height: 40px;
  border: 2px solid var(--color-accent-primary);
  border-radius: 50%;
  margin: 0 auto var(--spacing-md);
  animation: scan 1.5s ease-in-out infinite;
}

@keyframes scan {
  0%, 100% { transform: scale(1); opacity: 1; }
  50% { transform: scale(1.2); opacity: 0.5; }
}

.leaderboard-list {
  display: flex;
  flex-direction: column;
  gap: var(--spacing-sm);
}

.leaderboard-item {
  display: flex;
  align-items: center;
  gap: var(--spacing-sm);
  padding: var(--spacing-sm);
  background: rgba(255, 255, 255, 0.03);
  border: 1px solid rgba(255, 255, 255, 0.08);
  cursor: pointer;
  transition: all 0.3s ease;
  position: relative;
  overflow: hidden;
  text-align: left;
  width: 100%;
}

.leaderboard-item:hover {
  background: rgba(255, 255, 255, 0.06);
  border-color: var(--color-accent-primary);
  transform: translateX(4px);
}

.leaderboard-item.top-1 {
  border-color: #FFD700;
  background: rgba(255, 215, 0, 0.05);
}

.leaderboard-item.top-2 {
  border-color: #C0C0C0;
  background: rgba(192, 192, 192, 0.05);
}

.leaderboard-item.top-3 {
  border-color: #CD7F32;
  background: rgba(205, 127, 50, 0.05);
}

.rank-section {
  display: flex;
  align-items: center;
  gap: var(--spacing-sm);
  flex-shrink: 0;
}

.rank-badge {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 28px;
  height: 28px;
  background: rgba(255, 255, 255, 0.1);
  font-family: var(--font-family-heading);
  font-weight: 800;
  font-size: 1rem;
  color: white;
  flex-shrink: 0;
}

.country-flag-large {
  font-size: 2.5rem;
  line-height: 1;
  flex-shrink: 0;
}

.country-info {
  flex: 1;
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.country-name-row {
  display: flex;
  align-items: center;
  gap: var(--spacing-xs);
  min-width: 0;
}

.country-name {
  font-family: var(--font-family-heading);
  font-size: clamp(0.9rem, 3vw, 1.1rem);
  color: white;
  font-weight: 700;
  text-transform: uppercase;
  line-height: 1.1;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  flex: 1;
  min-width: 0;
}

.country-stats {
  display: flex;
  align-items: baseline;
  gap: 4px;
  flex-wrap: wrap;
}

.stat-value {
  font-family: var(--font-family-heading);
  font-size: 1.2rem;
  font-weight: 700;
  color: var(--color-accent-tertiary);
}

.stat-value.highlight {
  color: var(--color-accent-primary);
  font-size: 1.4rem;
}

.stat-label {
  font-size: 0.6rem;
  font-weight: 800;
  color: rgba(255, 255, 255, 0.4);
  letter-spacing: 0.5px;
}

.separator {
  color: rgba(255, 255, 255, 0.3);
  margin: 0 4px;
}

.item-glitch {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: linear-gradient(90deg, transparent, var(--color-accent-primary), transparent);
  opacity: 0;
  transition: opacity 0.3s ease;
  pointer-events: none;
}

.leaderboard-item:hover .item-glitch {
  opacity: 0.1;
}

@keyframes race-in-right {
  from {
    opacity: 0;
    transform: translateX(100px);
  }
  to {
    opacity: 1;
    transform: translateX(0);
  }
}

@keyframes race-in-left {
  from {
    opacity: 0;
    transform: translateX(-100px);
  }
  to {
    opacity: 1;
    transform: translateX(0);
  }
}

.race-in-right {
  animation: race-in-right 0.6s cubic-bezier(0.16, 1, 0.3, 1);
}

.race-in-left {
  animation: race-in-left 0.6s cubic-bezier(0.16, 1, 0.3, 1);
}

@media (max-width: 768px) {
  .leaderboard-item {
    gap: var(--spacing-xs);
  }
  
  .country-flag-large {
    font-size: 2rem;
  }
}
</style>
